import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { WorkerResult } from '../types';

const WorkerCard: React.FC<{ result: WorkerResult }> = ({ result }) => {
  const [isOpen, setIsOpen] = useState(false);

  // Status colors
  const statusColor = 
    result.status === 'success' ? 'border-green-500/30 bg-green-900/10 text-green-400' :
    result.status === 'error' ? 'border-red-500/30 bg-red-900/10 text-red-400' :
    'border-blue-500/30 bg-blue-900/10 text-blue-400 animate-pulse';

  return (
    <div className={`border rounded-lg mb-3 overflow-hidden transition-all duration-200 ${isOpen ? 'border-slate-600 bg-slate-800/50' : 'border-slate-800 bg-slate-900'}`}>
      <button 
        onClick={() => setIsOpen(!isOpen)}
        className="w-full flex items-center justify-between p-4 text-left hover:bg-slate-800 transition-colors"
      >
        <div className="flex flex-col md:flex-row md:items-center gap-2 md:gap-4 overflow-hidden">
          <div className="flex items-center gap-3">
            <div className={`shrink-0 w-2 h-2 rounded-full ${result.status === 'success' ? 'bg-green-500' : result.status === 'error' ? 'bg-red-500' : 'bg-blue-500'}`} />
            <span className="font-semibold text-slate-200 text-sm md:text-base truncate">{result.expert.name}</span>
          </div>
          <span className="hidden md:inline text-slate-600">|</span>
          <span className="text-xs text-brand-400 font-mono uppercase tracking-wide truncate max-w-[200px] md:max-w-none">
            {result.expert.role}
          </span>
          {result.groundingUrls && result.groundingUrls.length > 0 && (
             <span className="hidden md:flex items-center gap-1 text-[10px] bg-slate-800 text-slate-400 px-2 py-0.5 rounded-full border border-slate-700">
                <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
                Verified
             </span>
          )}
          {result.executionTime && (
            <span className="text-xs text-slate-500 font-mono ml-auto md:ml-2">
              {result.executionTime}ms
            </span>
          )}
        </div>
        <div className="flex items-center gap-2 pl-2">
            <span className={`text-[10px] md:text-xs px-2 py-0.5 rounded border ${statusColor}`}>
                {result.status.toUpperCase()}
            </span>
            <svg className={`w-4 h-4 text-slate-400 transform transition-transform ${isOpen ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
            </svg>
        </div>
      </button>
      
      {isOpen && (
        <div className="p-4 border-t border-slate-700/50 bg-slate-950/30">
            <div className="mb-4 flex flex-wrap items-center gap-3 text-xs text-slate-500 italic">
                <div className="flex items-center gap-2">
                    <span className="bg-slate-800 px-2 py-0.5 rounded text-slate-400">Persona</span>
                    {result.expert.description}
                </div>
            </div>
            
            {/* Image Display */}
            {result.images && result.images.length > 0 && (
              <div className="mb-6 grid grid-cols-1 gap-4">
                {result.images.map((img, idx) => (
                  <div key={idx} className="relative rounded-lg overflow-hidden border border-slate-700 group">
                    <img 
                      src={`data:image/jpeg;base64,${img}`} 
                      alt={`Generated by ${result.expert.name}`} 
                      className="w-full h-auto object-cover"
                    />
                    <a 
                      href={`data:image/jpeg;base64,${img}`}
                      download={`generated-image-${Date.now()}.jpg`}
                      className="absolute top-2 right-2 bg-slate-900/80 text-white p-2 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity hover:bg-black"
                      title="Download Image"
                    >
                       <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                    </a>
                  </div>
                ))}
              </div>
            )}
            
            {/* Grounding Sources (Google Search Results) */}
            {result.groundingUrls && result.groundingUrls.length > 0 && (
                <div className="mb-4 p-3 bg-slate-900/50 rounded-lg border border-slate-800">
                    <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2 flex items-center gap-2">
                        <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" /></svg>
                        Sources
                    </div>
                    <div className="flex flex-wrap gap-2">
                        {result.groundingUrls.map((source, i) => (
                            <a 
                                key={i} 
                                href={source.uri} 
                                target="_blank" 
                                rel="noopener noreferrer"
                                className="inline-flex items-center gap-1.5 px-2 py-1 rounded bg-slate-800 text-blue-400 hover:text-blue-300 text-xs transition-colors truncate max-w-[200px]"
                            >
                                <span className="truncate">{source.title}</span>
                            </a>
                        ))}
                    </div>
                </div>
            )}

            <div className="text-slate-300 text-sm">
             {result.content ? (
                <ReactMarkdown 
                    remarkPlugins={[remarkGfm]}
                    className="prose prose-invert prose-sm max-w-none 
                        prose-pre:bg-black/50 prose-pre:border prose-pre:border-slate-800
                        prose-code:text-brand-200 prose-code:before:content-none prose-code:after:content-none
                        prose-a:text-brand-400"
                >
                    {result.content}
                </ReactMarkdown>
             ) : (
                 <span className="animate-pulse text-slate-500">Waiting for response...</span>
             )}
          </div>
        </div>
      )}
    </div>
  );
};

export const WorkerAccordion: React.FC<{ results: WorkerResult[] }> = ({ results }) => {
  return (
    <div className="mt-8 border-t border-slate-800 pt-8">
      <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-4 flex items-center gap-2">
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" /></svg>
        Expert Deliberation ({results.length})
      </h3>
      <div className="grid grid-cols-1 gap-2">
        {results.map((result) => (
          <WorkerCard key={result.expert.id} result={result} />
        ))}
      </div>
    </div>
  );
};